Imports System.Data
Imports System.Data.SqlClient

Imports System.IO
Imports System.Net
Imports System.Globalization
Imports ClosedXML.Excel
Partial Class App_UI_Application_Pages_GenerateEPReport
    Inherits System.Web.UI.Page
    Dim objDAL As DAL
    Dim dt As New DataTable
    Dim objGen As clsGeneral = New clsGeneral

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        objDAL = New DAL(HttpContext.Current.Session("MlmDatabase" & Session("CompID")))
        Try
            If Session("AStatus") = "OK" Then
            Else
                Response.Redirect("logout.aspx")
            End If

            If Not Page.IsPostBack Then
               

            End If


        Catch ex As Exception

        End Try
    End Sub

    


    Private Sub FillReport()
        Try

            Dim sql As String = String.Empty





            'sql = " Select (Case When Formno = '0' then 'Admin' Else Convert(Varchar,Formno) End) As IDno , 'Admin'  As Name ,EP,"
            'sql &= "  (Case When VcType = 'C' then 'Credit' Else 'Debit' End) [Voucher Type] , "
            'sql &= "  Replace(CONVERT( Varchar, AddDate,106),' ','-') As Date,Remark "
            'sql &= "  from M_GenerateEPHistory"
            'sql &= "  Where Formno = 0 "
            'If (txtStartDate.Text <> "" Or txtEndDate.Text <> "") Then
            '    sql &= " And  Cast(AddDate  As DATE) >= '" & txtStartDate.Text & "'"
            '    sql &= " And  Cast(AddDate  As DATE) <= '" & txtEndDate.Text & "'"
            'End If



            'sql &= "  Union All"

            'sql &= "  Select b.Idno As IDno ,  b.MemFirstName As Name ,EP,"
            'sql &= "  (Case When VcType = 'C' then 'Credit' Else 'Debit' End) [Voucher Type] , "
            'sql &= "  Replace(CONVERT( Varchar, AddDate,106),' ','-') As Date,Remark "
            'sql &= "  from M_GenerateEPHistory a Inner join   M_memberMAster  b on  a.Formno = b.Formno"
            'sql &= "  Where a.Formno <> 0 "
            'If (txtStartDate.Text <> "" Or txtEndDate.Text <> "") Then
            '    sql &= " And  Cast(AddDate  As DATE) >= '" & txtStartDate.Text & "'"
            '    sql &= " And  Cast(AddDate  As DATE) <= '" & txtEndDate.Text & "'"
            'End If


            sql = " Select * from ("
            sql &= "  Select AddDate As Date,(Case When Formno = '0' then 'Admin' Else Convert(Varchar,Formno) End) As IDno , ' Ep Generated By  Admin'  As Name ,EP As [EP Credit] , 0 [EP Debit], Balance,"
            'sql &= "  (Case When VcType = 'C' then 'Credit' Else 'Debit' End) [Voucher Type] , "
            sql &= "  Remark "

            sql &= "  from M_GenerateEPHistory"
            sql &= "  Where Formno = 0 "
            If (txtStartDate.Text <> "" Or txtEndDate.Text <> "") Then
                sql &= " And  Cast(AddDate  As DATE) >= '" & txtStartDate.Text & "'"
                sql &= " And  Cast(AddDate  As DATE) <= '" & txtEndDate.Text & "'"
            End If

            sql &= "  Union All"

            sql &= "  Select AddDate As Date,b.Idno As IDno ,  b.MemFirstName As Name , (Case When VcType = 'C' then  EP  Else '0' End) As [EP Credit] , "
            sql &= "  (Case When VcType = 'D' then  EP  Else '0' End) As [EP Debit], Balance,"
            'sql &= "  (Case When VcType = 'C' then 'Credit' Else 'Debit' End) [Voucher Type] , "
            sql &= "  Remark"
            sql &= "  from M_GenerateEPHistory a Inner join   M_memberMAster  b on  a.Formno = b.Formno"
            sql &= "  Where a.Formno <> 0"

            If (txtStartDate.Text <> "" Or txtEndDate.Text <> "") Then
                sql &= " And  Cast(AddDate  As DATE) >= '" & txtStartDate.Text & "'"
                sql &= " And  Cast(AddDate  As DATE) <= '" & txtEndDate.Text & "'"
            End If
            sql &= "  ) As temp "
            sql &= "  Order by DAte"










            objDAL = New DAL(HttpContext.Current.Session("MlmDatabase" & Session("CompID")))
            dt = objDAL.GetData(sql)
            GvData.DataSource = dt
            GvData.DataBind()

            Session("GData") = dt
        Catch ex As Exception

        End Try
    End Sub





    



    Protected Sub btnSearch_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnSearch.Click
  
        FillReport()


    End Sub

    Protected Sub GvData_PageIndexChanging(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewPageEventArgs) Handles GvData.PageIndexChanging
        GvData.PageIndex = e.NewPageIndex
       
        FillReport()

    End Sub


    Protected Sub btnExport_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnExport.Click
        Try

           
            FillReport()

            ExportExcel()

        Catch ex As Exception
            Response.Write(ex.Message & "Error In Exporting File")

        End Try
    End Sub

    Private Sub ExportExcel()
        Dim dt As DataTable = Session("GData")
        Using wb As New XLWorkbook()
            wb.Worksheets.Add(dt, "Incentive")
            Response.Clear()
            Response.Buffer = True
            Response.Charset = ""
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            Response.AddHeader("content-disposition", "attachment;filename=IncentiveDetail.xlsx")
            Using MyMemoryStream As New MemoryStream()
                wb.SaveAs(MyMemoryStream)
                MyMemoryStream.WriteTo(Response.OutputStream)
                Response.Flush()
                Response.End()
            End Using
        End Using

    End Sub


End Class


